blank_issues_enabled: false
contact_links:
    - name: Question 🤷
      url: https://github.com/gemini-testing/hermione/discussions
      about: Ask questions and discuss with other community members
    - name: My company is migrating to Hermione and we have several issues/feature requests
      url: https://github.com/gemini-testing/hermione/discussions/838
